name: 'SFTP Deploy Action'
description: 'Deploy files to a server via SFTP.'
author: 'dacong-wu'
inputs:
  SFTP_HOST:
    description: 'The SFTP host.'
    required: true
  SFTP_USERNAME:
    description: 'The SFTP username.'
    required: true
  SFTP_PASSWORD:
    description: 'The SFTP password.'
    required: false
  SFTP_PRIVATEKEY:
    description: 'The SFTP privateKey'
    required: false
  SFTP_REMOTE:
    description: 'The remote directory on the SFTP server.'
    required: true
  BACKUP:
    description: 'Backup the previous version.'
    required: false
    default: true
runs:
  using: 'node20'
  main: 'deploy-to-sftp.js'
